### PR TITLE
Develop

### LINKED ISSUE #2: Investigate about Wiki in GitHub

### LINKED ISSUE #6: Investigate about project board

### LINKED ISSUE #8: Investigate package in npm

### LINKED ISSUE #11: Investigate GitHub REST API
Document in the branch develop

Links:
https://docs.github.com/en/rest

### LINKED ISSUE #12: Add more FAQs

### LINKED ISSUE #15: Propose GitActions templates

### LINKED ISSUE #20: Translate README.md to French

### PR DESCRIPTION
**Pull request by Alespitale**
Termine dos tarjetas:
Wiki in github
Project Board

### CODE REVIEW

**Comment by shirosweets** [comment]
@Alespitale Link issues

**Comment by shirosweets** [comment]
@Alespitale Remember link issues
**Here:**
image

Or write the link in the conversation ✍️

**Review by shirosweets — CHANGES_REQUESTED** [review]
1. Rename `README-French.md` to `README_FR.md`
2. Add file `EEEE`
3. Remove `~` in all **md** files
4. Change `MENU` to `Index`
5. Rewrite `owl/eye/Api_rest.md` to **EN** and remember that "investigate" is:
> What is? (always)

> How works? (always)

> Features

  > [Packages](https://docs.github.com/en/rest/reference/packages)

  > [Issues](https://docs.github.com/en/rest/reference/issues)

  > Git Database

  > [SCIM](https://docs.github.com/en/rest/reference/scim)

  > Limit rates (for [example](https://docs.github.com/en/rest/reference/search#rate-limit))

**Review by shirosweets — CHANGES_REQUESTED** [review]
1. Rename:
- `Github-Actions_templates.webp` to `github-Actions_templates.webp`
- `Repository-templates.md` to repository-templates.md
- `Api_rest_github.md` to `api_rest_github.md`

**Comment by Alespitale** [comment]
Bueno chicos ya termine lo que me pidieron, mas tarde hago lo de los endpoints

**Comment by Alespitale** [comment]
>     1. Rename `README-French.md` to `README_FR.md`
> 
>     2. Add file `EEEE`
> 
>     3. Remove `~` in all **md** files
> 
>     4. Change `MENU` to `Index`
> 
>     5. Rewrite `owl/eye/Api_rest.md` to **EN** and remember that "investigate" is:
> 
> 
> > What is? (always)
> 
> > How works? (always)
> 
> > Features
> 
> > [Packages](https://docs.github.com/en/rest/reference/packages)
> 
> > [Issues](https://docs.github.com/en/rest/reference/issues)
> 
> > Git Database
> 
> > [SCIM](https://docs.github.com/en/rest/reference/scim)
> 
> > Limit rates (for [example](https://docs.github.com/en/rest/reference/search#rate-limit))

Listo

**Review by shirosweets — APPROVED** [review]

**Comment by shirosweets** [comment]
@AgustinMDominguez

**Review by AgustinMDominguez — APPROVED** [review]
👍🏻

**Pull request merged**
